// <auto-generated />
using System;
using ArmatuXPC.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArmatuXPC.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260426163912_FixCapacidadWattsToDecimal")]
    partial class FixCapacidadWattsToDecimal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArmatuXPC.Backend.Models.Armado", b =>
                {
                    b.Property<int>("ArmadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArmadoId"));

                    b.Property<string>("AutorNombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsPublicado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("NombreArmado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ArmadoId");

                    b.ToTable("Armados");
                });

            modelBuilder.Entity("ArmatuXPC.Backend.Models.ArmadoComponente", b =>
                {
                    b.Property<int>("ArmadoId")
                        .HasColumnType("integer");

                    b.Property<int>("ComponenteId")
                        .HasColumnType("integer");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.HasKey("ArmadoId", "ComponenteId");

                    b.HasIndex("ComponenteId");

                    b.ToTable("ArmadoComponentes");
                });

            modelBuilder.Entity("ArmatuXPC.Backend.Models.Compatibilidad", b =>
                {
                    b.Property<int>("CompatibilidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CompatibilidadId"));

                    b.Property<int>("ComponenteAId")
                        .HasColumnType("integer");

                    b.Property<int>("ComponenteBId")
                        .HasColumnType("integer");

                    b.Property<bool>("EsCompatible")
                        .HasColumnType("boolean");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CompatibilidadId");

                    b.HasIndex("ComponenteAId");

                    b.HasIndex("ComponenteBId");

                    b.ToTable("Compatibilidades");
                });

            modelBuilder.Entity("ArmatuXPC.Backend.Models.Componente", b =>
                {
                    b.Property<int>("ComponenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ComponenteId"));

                    b.Property<decimal?>("CapacidadWatts")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("ConsumoWatts")
                        .HasColumnType("decimal(10,2)");

                    b.Property<bool>("EstaActivo")
                        .HasColumnType("boolean");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("text");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("ComponenteId");

                    b.ToTable("Componentes");
                });

            modelBuilder.Entity("ArmatuXPC.Backend.Models.Usuario", b =>
                {
                    b.Property<string>("Uid")
                        .HasColumnType("text");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TokensDisponibles")
                        .HasColumnType("integer");

                    b.HasKey("Uid");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("FeedbackUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comentario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool?>("CompletoSinAyuda")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("TipoHito")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioUid")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("ArmatuXPC.Backend.Models.ArmadoComponente", b =>
                {
                    b.HasOne("ArmatuXPC.Backend.Models.Armado", "Armado")
                        .WithMany("Componentes")
                        .HasForeignKey("ArmadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ArmatuXPC.Backend.Models.Componente", "Componente")
                        .WithMany("Armados")
                        .HasForeignKey("ComponenteId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Armado");

                    b.Navigation("Componente");
                });

            modelBuilder.Entity("ArmatuXPC.Backend.Models.Compatibilidad", b =>
                {
                    b.HasOne("ArmatuXPC.Backend.Models.Componente", "ComponenteA")
                        .WithMany()
                        .HasForeignKey("ComponenteAId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ArmatuXPC.Backend.Models.Componente", "ComponenteB")
                        .WithMany()
                        .HasForeignKey("ComponenteBId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ComponenteA");

                    b.Navigation("ComponenteB");
                });

            modelBuilder.Entity("ArmatuXPC.Backend.Models.Armado", b =>
                {
                    b.Navigation("Componentes");
                });

            modelBuilder.Entity("ArmatuXPC.Backend.Models.Componente", b =>
                {
                    b.Navigation("Armados");
                });
#pragma warning restore 612, 618
        }
    }
}
