// <auto-generated />
using ArmatuXPC.Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArmatuXPC.Backend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArmatuXPC.Backend.Models.Armado", b =>
                {
                    b.Property<int>("ArmadoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ArmadoId"));

                    b.Property<int>("AlmacenamientoId")
                        .HasColumnType("integer");

                    b.Property<int>("FuentePoderId")
                        .HasColumnType("integer");

                    b.Property<int>("GPUId")
                        .HasColumnType("integer");

                    b.Property<int>("GabineteId")
                        .HasColumnType("integer");

                    b.Property<int>("MemoriaRamId")
                        .HasColumnType("integer");

                    b.Property<string>("NombreArmado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlacaBaseId")
                        .HasColumnType("integer");

                    b.Property<int>("ProcesadorId")
                        .HasColumnType("integer");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("ArmadoId");

                    b.ToTable("Armados");
                });

            modelBuilder.Entity("ArmatuXPC.Backend.Models.Compatibilidad", b =>
                {
                    b.Property<int>("CompatibilidadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CompatibilidadId"));

                    b.Property<int>("ComponenteId")
                        .HasColumnType("integer");

                    b.Property<string>("MarcaComponente")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MarcaIncompatible")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RazonIncompatibilidad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("CompatibilidadId");

                    b.HasIndex("ComponenteId");

                    b.ToTable("Compatibilidades");
                });

            modelBuilder.Entity("ArmatuXPC.Backend.Models.Componente", b =>
                {
                    b.Property<int>("ComponenteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ComponenteId"));

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<decimal>("Voltaje")
                        .HasColumnType("numeric");

                    b.HasKey("ComponenteId");

                    b.ToTable("Componentes");
                });

            modelBuilder.Entity("ArmatuXPC.Backend.Models.Compatibilidad", b =>
                {
                    b.HasOne("ArmatuXPC.Backend.Models.Componente", "Componente")
                        .WithMany()
                        .HasForeignKey("ComponenteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Componente");
                });
#pragma warning restore 612, 618
        }
    }
}
